#!/usr/bin/env bash

print_domain_subdomain () {
    domain="$1"
    subdomain="$2"
    dig_output=$(dig "$subdomain.$domain" +short)
    if [ -z "$dig_output" ]; then
        echo "No record found for $subdomain.$domain"
    else
        record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ {getline; print $4}')
        destination=$(echo "$dig_output")
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$1" "$2"
elif [ "$#" -eq 1 ]; then
    domain="$1"
    print_domain_subdomain "$domain" "www"
    print_domain_subdomain "$domain" "lb-01"
    print_domain_subdomain "$domain" "web-01"
    print_domain_subdomain "$domain" "web-02"
else
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi
