#!/usr/bin/env bash

print_domain_subdomain() {
    domain="$1"
    subdomain="$2"
    dig_output=$(dig "$subdomain.$domain" +short)
    if [ -z "$dig_output" ]; then
        echo "No record found for $subdomain.$domain"
    else
        while read -r line; do
            record_type=$(echo "$line" | awk '{print $4}')
            destination=$(echo "$line" | awk '{print $5}')
            echo "The subdomain $subdomain is a $record_type record and points to $destination"
        done <<< "$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ {getline; print}')"
    fi
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$1" "$2"
elif [ "$#" -eq 1 ]; then
    domain="$1"
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        print_domain_subdomain "$domain" "$subdomain"
    done
else
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi
