#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page with a 301 Moved Permanently

# Update package lists and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a simple HTML page
echo "Hello World" | sudo tee /var/www/html/index.html

# Create a new Nginx configuration file for redirection
sudo bash -c 'cat > /etc/nginx/sites-available/redirect_me' <<EOF
server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}
EOF

# Create a symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Remove the default configuration to avoid conflicts
sudo rm /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
