#!/usr/bin/env bash
# Configure Nginx server to redirect /redirect_me to another page using 301 Moved Permanently

# Install Nginx
apt-get update
apt-get install -y nginx

# Create a temporary configuration file for redirection
cat <<EOF > /etc/nginx/sites-available/redirect_me
server {
    listen 80;
    listen [::]:80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Enable the redirection site
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration
nginx -t

# Restart Nginx
service nginx restart
