#!/usr/bin/env bash

# Install nginx on your web-01 server
apt-get -y update
apt-get -y install nginx

# Create a custom 404 page with the required string
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Configure Nginx to use the custom 404 page
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}

EOF

# Restart nginx to apply changes
service nginx restart
