#!/usr/bin/env bash
# Configure Nginx server with a custom 404 page

# Update package lists
apt-get -y update

# Install Nginx
apt-get -y install nginx

# Create custom 404 page with required content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Configure Nginx to use the custom 404 page
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
