#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page

# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Create custom 404 page with required content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Configure Nginx to use the custom 404 page
cat << 'EOF' > /etc/nginx/sites-available/custom_404
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    error_page 404 /custom_404.html;

    location = /custom_404.html {
        internal;
        try_files $uri =404;
    }
}
EOF

# Enable the custom configuration and disable the default configuration
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/
rm /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
service nginx restart
