#!/usr/bin/env bash
# Configures Nginx with a custom HTTP response header

# Install Nginx
apt-get update
apt-get install -y nginx

# Retrieve hostname
hostname=$(hostname)

# Configure Nginx
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $hostname;
    root /var/www/html;
    index index.html index.htm;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart Nginx
systemctl restart nginx
