#!/usr/bin/env bash
# configures a new Ubuntu machine

# Install nginx on web-01 server
apt-get -y update
apt-get -y install nginx

# Add custom response header to know the server name for debugging
HOST_NAME=$(hostname)
HEADER="\\\n\tadd_header X-Served-By $HOST_NAME;\n"
if ! grep -q "X-Served-By" /etc/nginx/sites-available/default; then
    sed -i '/server_name _;/a '"$HEADER"'' /etc/nginx/sites-available/default
fi

# Create the first index.html page
echo "Hello World!" > /var/www/html/index.html

# Add to the nginx configuration file a redirection to another page
if ! grep -q "redirect_me" /etc/nginx/sites-available/default; then
    REDIRECT_STRING="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}\n"
    sed -i '/location \/ {/a '"$REDIRECT_STRING"'' /etc/nginx/sites-available/default
fi

# Add to the nginx configuration file an error page 404
if ! grep -q "error_page 404" /etc/nginx/sites-available/default; then
    ERROR="\\\n\terror_page 404 /custom_404.html;\n"
    echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
    sed -i '/location \/ {/a '"$ERROR"'' /etc/nginx/sites-available/default
fi

service nginx restart
