#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy

# Adjust HAProxy configuration
echo "
frontend hassankyanziweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 68597-web-01 18.204.8.93:80 check
    server 68597-web-02 54.167.152.52:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# Restart HAProxy service
sudo service haproxy restart
