#!/usr/bin/env bash
# Server login script

# setting up ssh agent
eval $("ssh-agent")

#Path to  identify file
ssh-add ~/home/hassan-kyanzi/.ssh/id_rsa

#Username and IP Address
ssh -v ubuntu@54.167.152.52